name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: 'pandemic-console/web/package-lock.json'
    - run: npm install
      working-directory: pandemic-console/web
    - run: cargo build --workspace
    - run: cargo test --workspace
    - run: cargo clippy --workspace -- -D warnings
    - run: cargo fmt --check